//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Joole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public int ProductID { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
        public string ProductName { get; set; }
        public int ProductYear { get; set; }
        public string ProductImage { get; set; }
    
        public virtual tblSubCategory tblSubCategory { get; set; }
    }
}
